# Change these first
owner: invig
repo: startrisk-uptime
user-agent: invig

sites:
  - name: StartRisk
    url: https://www.startrisk.com
  - name: StartRisk Services
    url: $SERVICES_PING
  - name: StartRisk Storage
    url: $SERVICES_SUPABASE_PING

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.startrisk.com
  # baseUrl: /startrisk-uptime
  logoUrl: https://startrisk.com/assets/assets/Logo/HeaderLogo.png
  theme: light
  favicon: https://startrisk.com/favicon.png
  css: ".logo img { height: 21.5px !important; width: 150px; } .logo div { display: none } body { background-color: #FFF; } footer { display: none }"
  name: StartRisk Status
  navbar:
    - title: Back to StartRisk
      href: https://www.startrisk.com/


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
