# Change these first
owner: invig # Your GitHub organization or username, where this repository lives
repo: startrisk-uptime # The name of this repository

sites:
  - name: StartRisk
    url: https://www.startrisk.com
  - name: StartRisk Services
    url: $SERVICES_PING
  - name: Supabase
    url: $SERVICES_SUPABASE_PING

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.startrisk.com
  # baseUrl: /your-repo-name
  logoUrl: https://startrisk.com/assets/assets/Logo/HeaderLogo.png
  name: StartRisk Status
  introTitle: "StarRisk Uptime Monitor"
  introMessage: "Hopefully there's a lot of green, if not you can contact support@startrisk.com for help."
  navbar:
    - title: StartRisk Status
      href: /
    - title: StartRisk
      href: https://www.startrisk.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
